POST http://localhost:3000/attraction HTTP/1.1
content-type: application/json

{
    "name": "Fenway Park",
    "webpage": "www.tufts.edu",
    "phone": "(617)627-5000",
    "street": "419 Boston Avenue",
    "city": "Medford",
    "state": "MA",
    "zip": "02155",
    "description": "Tufts University is a private research university located in the Greater Boston area. The main campus is located in the Walnut Hill neighborhood of the towns of Medford and Somerville, Massachusetts, with additional facilities located in Boston and Grafton, Massachusetts, and in Talloires, France. It was founded in 1852 as Tufts College by Christian universalists who sought to provide a nonsectarian institution of higher learning. Tufts remained a small liberal arts college until the 1970s, when it transformed into a large research university offering several doctorates. Tufts offers over 90 undergraduate and 160 graduate programs across ten schools in the greater Boston area and Talloires, France.",
    "years": "4",
    "costAfterAid": "36000",
    "graduationRate": "94",
    "acceptanceRate": "11",
    "sportingAffiliations": "NCAA Division III - NESCAC - NEISA"
}