POST  http://localhost:3000/health HTTP/1.1
content-type: application/json

{
  "name": "Boston College Trial ",
  "webpage": "bc.edu",
  "phone": "(617)552-8000",
  "street": "140 Commonwealth Avenue",
  "city": "Chestnut Hill",
  "state": "MA",
  "zip": "02467",
  "description": "In 2003, after years of student-led discussions and efforts, and administrators' repeated rejection of pleas from students, the school approved a Gay-Straight Alliance, the first university-funded gay support group on campus. In 2004, between 1,000 and 1,200 students rallied behind a student-led campaign to expand the school's non-discrimination statement to include equal protection for gays and lesbians.[24] Earlier that year 84% of the student body voted in favor of a student referendum calling for a change in policy.[25] After several months of discussion the university changed its statement of nondiscrimination to make it more welcoming to gay students in May 2005, but stopped short of prohibiting discrimination on the basis of sexual orientation",
  "years": "4",
  "costAfterAid": "38000",
  "graduationRate": "94",
  "acceptanceRate": "19",
  "sportingAffiliations": "NCAA Division I FBS - ACC Hockey East NEISA EISA EAWRC"
}